//! Report templates
//!
//! Template configuration shared by report generators.
//! HTML/Markdown rendering currently lives in `generator.rs`.

/// Template configuration
pub struct TemplateConfig {
    pub include_evidence: bool,
    pub include_remediation: bool,
    pub company_logo: Option<String>,
    pub footer_text: Option<String>,
}

impl Default for TemplateConfig {
    fn default() -> Self {
        Self {
            include_evidence: true,
            include_remediation: true,
            company_logo: None,
            footer_text: Some("Generated by AegisOSINT".to_string()),
        }
    }
}
